/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 temmy_capoeira.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/temmy_capoeira.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions.capoeira.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Tem_Body" geometry={nodes.Tem_Body.geometry} material={materials['Material.002']} skeleton={nodes.Tem_Body.skeleton} />
        </group>
        <mesh name="Ch33_Eyelashes" geometry={nodes.Ch33_Eyelashes.geometry} material={materials.Ch33_hair} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/temmy_capoeira.glb')

export default Model;